import {AppHeader} from "../AppHeader";
import {AppFooter} from "../AppFooter";

export function TermsPage() {
    const company = "Source Code Owner";
    const service = "Tach Game Engine";
    const url = "tach.io";
    return <>
        <div className="container mx-auto px-4">
            <AppHeader/>
            <h2> Terms of Service </h2>
            <p>
                Last revised on 12/25/2022
            </p>
            <p>
                {company} operates the {service} service, which we hope you use. If you use it, please use it
                responsibly.
                If you don't, we'll have to terminate your account and access.
            </p>
            <p>
                For paid accounts, you'll be charged on a monthly basis. You can cancel anytime, but there are no
                refunds.
            </p>
            <p>
                The Terms of Service, {service} itself, and our prices can change at any time. We'll warn you 30 days in
                advance of any price changes. We'll try to warn you about major changes to the Terms of Service
                or {service},
                but we make no guarantees.
            </p>
            <p>
                That's the basic idea, but You must read through the entire Terms of Service below and agree with all
                the
                details before You use any of our sites (whether or not you have created an account).
                Reuse
            </p>
            <p>
                Your use of the {company} service is governed by this agreement (the "Terms"). "{company}" means the
                lawful
                agent behind {company}. The "Service" means the services {company} makes available include our web sites
                ({url}), our blog, our API, and any other software, sites, and services offered by {company} in
                connection
                to any of those. "Customer Source Code" means any source code you submit to {company} for the purpose of
                using the Service. "Content" means all content generated by {company} on your behalf (including metric
                data)
                and does not include Customer Source Code.
            </p>
            <p>
                In order to use the Service, You (the "Customer", "You", or "Your") must first agree to the Terms. You
                understand and agree that {company} will treat Your use of the Service as acceptance of the Terms from
                that
                point onwards.
            </p>
            <p>
                {company} may make changes to the Terms from time to time. You may reject the changes by terminating
                Your
                account. You understand and agree that if You use the Service after the date on which the Terms have
                changed, {company} will treat Your use as acceptance of the updated Terms.
            </p>
            <p>
                If you have any question about the Terms, please contact us at mbostwick89 at google-mail dot com
            </p>
            <h3>
                Your Account
            </h3>
            <p>
                You may not use the Service if You are a person barred from receiving the Service under the laws of the
                United States or other countries, including the country in which You are resident or from which You use
                the
                Service.
                You may not use the service unless you are over the age of 13 or are named Darwin Michael Bostwick or
                Kepler
                Bostwick.
                You must be a human. Account created by automated methods are not permitted.
            </p>
            <h3>
                Use of the Service
            </h3>
            <p>
                You must provide accurate and complete registration information any time You register to use the
                Service.
                You are responsible for the security of Your passwords and for any use of Your account.
                Your use of the Service must comply with all applicable laws, regulations and ordinances.
                You agree to not engage in any activity that interferes with or disrupts the Service.
                {company} reserves the right to enforce quotas and usage limits (to any resources, including the API) at
                its
                sole discretion, with or without notice, which may result in {company} disabling or throttling your
                usage of
                the Service for any amount of time.
                You may not allow multiple people to use the same account or otherwise access the Service in a manner
                intended to avoid incurring fees.
            </p>
            <h3>
                Service Policies and Privacy
            </h3>
            <p>
                The Service shall be subject to the privacy policy for the Service available at privacy policy. You
                agree to
                the use of Your data in accordance with {company}'s privacy policies.
                Fees for Use of the Service
            </p>
            <p>
                The Service may be provided to You without charge up with certain limits or for a certain "trial" period
                of
                time.
                Usage over this limit (or after the "trial" period) requires Your purchase of additional resources or
                services.
                For all purchased resources and services, we will charge Your credit card on a monthly basis.
                Payments are non-refundable. There will be no refunds or credits for partial months of service,
                upgrade/downgrade refunds, or refunds for months unused with an open account.
                Charges are solely based on {company}'s measurements of Your use of the Service, unless otherwise agreed
                to
                in writing.
                All fees are exclusive of all taxes, levies, or duties imposed by taxing authorities, and You shall be
                responsible for payment of all such taxes, levies, or duties.
                You acknowledge and agree that any credit card and related billing and payment information that You
                provide
                to {company} may be shared by {company} with companies who work on {company}'s behalf, such as payment
                processors and/or credit agencies, solely for the purposes of checking credit, effecting payment
                to {company} and servicing Your account.
                {company} may change its fees and payment policies for the Service by notifying You at least thirty (30)
                days before the beginning of the billing cycle in which such change will take effect.
            </p>
            <h3>
                Cancellation and Termination
            </h3>
            <p>
                You must cancel Your account via {url}. An email or phone request to cancel Your account is not
                considered
                cancellation.
                You will not receive any refunds if You cancel Your account.
                If You cancel the Service before the end of Your current paid up month, Your cancellation will take
                effect
                immediately and You will not be charged again.
                All of Customer Source Code and Content will, within a reasonable amount of time to be determined solely
                by {company}, be deleted from the Service upon cancellation.
                You agree that {company}, in its sole discretion and for any or no reason, may terminate or suspend Your
                account. You agree that any termination of Your access to the Service may be without prior notice, and
                You
                agree that {company} will not be liable to You or any third party for such termination.
            </p>
            <h3>
                Customer Source Code
            </h3>
            <p>
                {company} claims no ownership or control over any Customer Source Code. You retain copyright and any
                other
                rights You already hold in the Customer Source Code and You are responsible for protecting those rights,
                as
                appropriate.
                You agree to assume full responsibility for configuring the Service to allow appropriate access to any
                Customer Source code provided to the Service.
                You understand that public projects display Customer Source Code to any party on the Internet, including
                search engines and web spiders.
                You understand that private projects will display Customer Source Code to You and any collaborators that
                you
                designate for that project.
                You retain sole responsibility for any collaborators or third-party services that you allow to view
                Customer
                Source Code and entrust them at your own risk.
                {company} is not responsible if you fail to configure, or misconfigure, your project and inadvertently
                allow
                unauthorized parties view any Customer Source Code.
            </p>
            <h3>
                Ideas and Feedback
            </h3>
            <p>
                You may choose to or we may invite You to submit comments or ideas about the Service, including but not
                limited to ideas about improving the Service or our products ("Ideas"). By submitting any Idea, You
                agree
                that Your disclosure is unsolicited and without restriction and will not place {company} under any
                fiduciary
                or other obligation, and that we are free to use the Idea without any additional compensation to You,
                and/or
                to disclose the Idea on a non-confidential basis or otherwise to anyone.
                Modification of the Service
            </p>
            <p>
                You acknowledge and agree that the Service may change from time to time without prior notice to You.
                Changes include, without limitation, changes to fee and payment policies, security patches, added or
                removed
                functionality, and other enhancements or restrictions.
                {company} shall not be liable to you or to any third party for any modification, price change,
                suspension or
                discontinuance of the Service.
            </p>
            <h3>
                External Resources
            </h3>
            <p>
                The Services may include hyperlinks to other web sites or content or resources or email content. You
                acknowledge and agree that {company} is not responsible for the availability of any such external sites
                or
                resources, and does not endorse any advertising, products or other materials on or available from such
                web
                sites or resources.
                License from {company} and Restrictions
            </p>
            <p>
                {company} gives You a personal, worldwide, royalty-free, non-assignable and non-exclusive license to use
                the
                software provided to You by {company} as part of the Service as provided to You by {company}. This
                license
                is for the sole purpose of enabling You to use and enjoy the benefit of the Service as provided
                by {company},
                in the manner permitted by the Terms.
            </p>
            <p>
                You may not (and You may not permit anyone else to): (a) copy, modify, create a derivative work of,
                reverse
                engineer, decompile or otherwise attempt to extract the source code of the Service or any part thereof,
                unless this is expressly permitted or required by law, or unless You have been specifically told that
                You
                may do so by {company}, in writing (e.g., through an open source software license); or (b) attempt to
                disable or circumvent any security mechanisms used by the Service.
            </p>
            <p>
                Open source software licenses for components of the Service released under an open source license
                constitute
                separate written agreements. To the limited extent that the open source software licenses expressly
                supersede these Terms, the open source licenses govern Your agreement with {company} for the use of the
                components of the Service released under an open source license.
                Exclusion of warranties
            </p>
            <p>
                You expressly understand and agree that your use of the service is at your sole risk and that the
                service is
                provided "as is" and "as available.".
                You agree that {company} has no responsibility or liability for the deletion or failure to store any
                Content
                and other communications maintained or transmitted through use of the Service. You further acknowledge
                that
                You are solely responsible for securing and backing up Customer Source Code.
                {company} does not warrant to you that: (a) your use of the service will meet your requirements, (b)
                your
                use of the service will be uninterrupted, timely, secure or free from error, (c) the results or data
                provided by the Service will be accurate, (d) the quality of the service will meet your expectations and
                (e)
                any errors in the Service will be fixed.
            </p>
            <h3>
                Limitation of liability
            </h3>
            <p>
                You expressly understand and agree that {company}, its subsidiaries and affiliates, and its licensors
                shall
                not be liable to you for any direct, indirect, incidental, special consequential or exemplary damages
                which
                may be incurred by you, however caused and under any theory of liability. This shall include, but not be
                limited to, any loss of profit (whether incurred directly or indirectly), any loss of goodwill or
                business
                reputation, any loss of data suffered, cost of procurement of substitute goods or services, or other
                intangible loss (whether or not {company} has been advised of or should have been aware of the
                possibility
                of any such losses arising).
                Indemnification
            </p>
            <p>
                You agree to hold harmless and indemnify {company}, and its subsidiaries, affiliates, officers, agents,
                employees, advertisers, licensors, suppliers or partners (collectively "{company} and Partners") from
                and
                against any third party claim arising from or in any way related to (a) Your breach of the Terms, (b)
                Your
                use of the Service, (c) Your violation of applicable laws, rules or regulations in connection with the
                Service, or (d) Your Customer Source Code, including any liability or expense arising from all claims,
                losses, damages (actual and consequential), suits, judgments, litigation costs and attorneys' fees, of
                every
                kind and nature. In such a case, {company} will provide You with written notice of such claim, suit or
                action.
            </p>
            <h3>
                General Legal Terms
            </h3>
            <p>
                The Terms constitute the whole legal agreement between You and {company} and govern Your use of the
                Service
                and completely replace any prior agreements between You and {company} in relation to the Service.
            </p>
            <p>
                You agree that if {company} does not exercise or enforce any legal right or remedy which is contained in
                the
                Terms (or which {company} has the benefit of under any applicable law), this will not be taken to be a
                formal waiver of {company}'s rights and that those rights or remedies will still be available
                to {company}.
            </p>
            <p>
                {company} shall not be liable for failing or delaying performance of its obligations resulting from any
                condition beyond its reasonable control, including but not limited to, governmental action, acts of
                terrorism, earthquake, fire, flood or other acts of God, labor conditions, power failures, and Internet
                disturbances.
            </p>
            <h3>
                Legal Entity Prohibition
            </h3>
            <p>
                If you are a member of any legal bar association, you are prohibited from using or accessing this site
                in
                any way with out written approval from the site owner.
            </p>
            <p>
                Any mention of this service or use of any content from this site in any legal documents requires written
                approval from the site owner.
            </p>
            <p>
                Any Legal Professional who fails to comply with this section is personally fiscally accountable for all litigation
                that is at all related to there choice to not get written approval and not make a good faith effort to resolve the concerns.
            </p>
            <AppFooter/>
        </div>
    </>
}
